.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPROCD_MODULE_PATH" "3" "January 2018" "" ""
.
.SH "NAME"
\fBuprocd_module_path\fR \- Retrieve the path to a file next to the current uprocd module
.
.SH "SYNOPSIS"
.
.nf

#include <uprocd\.h>

UPROCD_EXPORT char * uprocd_module_path(const char *path);
.
.fi
.
.SH "DESCRIPTION"
This function will retrieve the directory containing the current module\'s \.module file, then it will append the given path to that directory and return the result\. It is roughly equivalent to this:
.
.IP "" 4
.
.nf

// Same as uprocd_module_path("some\-file")
char *path = "some\-file";
char *directory = uprocd_module_directory();
char full_path[1024];
sprintf(full_path, "%s/%s", directory, path);
// full_path is the result\.
.
.fi
.
.IP "" 0
.
.P
The return value must be freed using \fBuprocd_module_path_free\fR(3)\.
.
.SH "RETURN VALUE"
The resulting path\. This function never fails\.
.
.SH "SEE ALSO"
uprocd\.index(7), uprocd\.h(3), uprocd_module_directory(3), uprocd_module_path_free(3)
