.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPROCD_ON_EXIT" "3" "January 2018" "" ""
.
.SH "NAME"
\fBuprocd_on_exit\fR \- Set a handler to be called on uprocd_run failure
.
.SH "SYNOPSIS"
.
.nf

#include <uprocd\.h>

typedef void (*uprocd_exit_handler)(void *userdata);
UPROCD_EXPORT void uprocd_on_exit(uprocd_exit_handler func, void *userdata);
.
.fi
.
.SH "DESCRIPTION"
This function will set a handler to be called if \fBuprocd_run\fR(3) fails\. This handler will only ever be called from the original parent process\.
.
.P
The given userdata will be passed to the handler when it is called\.
.
.SH "SEE ALSO"
uprocd\.index(7), uprocd\.h(3), uprocd_run(3)
