.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPROCD_CONTEXT_GET_ENV" "3" "January 2018" "" ""
.
.SH "NAME"
\fBuprocd_context_get_env\fR \- Retrieve the environment from a uprocd context
.
.SH "SYNOPSIS"
.
.nf

#include <uprocd\.h>

UPROCD_EXPORT const char ** uprocd_context_get_env(uprocd_context *ctx);
.
.fi
.
.SH "DESCRIPTION"
This functions will retrieve the environment of the \fBuprocctl\fR(1) process that called this module\.
.
.SH "RETURN VALUE"
A null\-terminated array of strings\. Each even index is an environment key, and each even value is the corresponding value\.
.
.SH "EXAMPLE"
.
.nf

const char **env = uprocd_context_get_env(ctx);
for (const char **p = env; *p != NULL; p += 2) {
  const char *key = p[0], *value = p[1];
  printf("%s=%s\en", key, value);
}
.
.fi
.
.SH "SEE ALSO"
uprocd\.index(7), uprocd\.h(3), uprocctl(1)
