.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPROCD_CONTEXT_ENTER" "3" "January 2018" "" ""
.
.SH "NAME"
\fBuprocd_context_enter\fR \- Enter a uprocd context object
.
.SH "SYNOPSIS"
.
.nf

#include <uprocd\.h>

UPROCD_EXPORT void uprocd_context_enter(uprocd_context *ctx);
.
.fi
.
.SH "DESCRIPTION"
This function will "enter" the given context\. The following operations will be performed:
.
.IP "1." 4
The current environment will be matched to the context\'s environment\.
.
.IP "2." 4
The current working directory will be changed to the context\'s working directory\.
.
.IP "3." 4
The current process will be attached to the context\'s standard I/O and terminal\.
.
.IP "" 0
.
.SH "SEE ALSO"
uprocd\.index(7), uprocd\.h(3), uprocd(7)
