.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPROCD\.INDEX" "7" "January 2018" "" ""
.
.SH "NAME"
\fBuprocd\.index\fR \- uprocd documentation index
.
.SH "RECOMMENDATIONS"
If you\'re just starting out, read \fBuprocd\fR(7) and \fBuprocctl\fR(1), which should send you well on your way\.
.
.SH "BASIC USAGE"
uprocd(7) \- Guide on managing uprocd modules with systemd
.
.P
uprocctl(1), u(1) \- Query or run uprocd modules
.
.SH "DEVELOPING MODULES"
uprocd\.module(5) \- uprocd module configuration format
.
.P
uprocd\.h(3) \- uprocd native module API index
