# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[NativeModule]
NativeLib=simple
ProcessName=simple

[Arguments]
String=string
Number=number
StringList=list string
NumberList=list number

[Defaults]
String=simple
Number=2
StringList=string list
NumberList=1 2 3
