# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[DerivedModule]
Base=python
Preload=import IPython
Run=
  from IPython.terminal.interactiveshell import TerminalInteractiveShell
  from IPython import start_ipython

  TerminalInteractiveShell.simple_prompt = False
  sys.exit(start_ipython())
